// <auto-generated />
namespace CarLot2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class carid2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carid2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404230228288_carid2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
